/**
 * 100 curated India fun facts — the same set used on the mobile app.
 * Displayed on loading screens to make wait time feel like learning.
 */
export const INDIA_FACTS: readonly string[] = [
  "India is the world's largest democracy, with over 900 million eligible voters.",
  "The game of chess is believed to have originated in India, originally called 'Chaturanga'.",
  "India has 22 officially recognized languages and hundreds more spoken regionally.",
  "The number zero as a mathematical concept was formalized by the Indian mathematician Aryabhata.",
  "India is home to the Bengal tiger, the country's national animal.",
  "The Taj Mahal took over 20,000 workers and about 22 years to build.",
  "India has the largest postal network in the world, with over 150,000 post offices.",
  "Yoga, a practice thousands of years old, originated in ancient India.",
  "India is the second-largest producer of fruits and vegetables in the world.",
  "The Indian Railways is one of the largest employers on Earth, with over a million employees.",
  "Kabaddi, a popular contact sport, originated in ancient India.",
  "India has 8 major religions, all born or deeply rooted within its borders.",
  "The Kumbh Mela, held in India, is the largest peaceful gathering of people on Earth.",
  "Snakes and Ladders was invented in India as a game called 'Moksha Patam'.",
  "India shares a border with six countries and has one of the longest coastlines in Asia.",
  "The mango is India's national fruit, and India grows more mangoes than any other country.",
  "India has the world's highest cricket ground, located in Chail, Himachal Pradesh.",
  "The lotus is India's national flower, symbolizing purity and beauty.",
  "India was the first country to reach the Moon's south polar region, with Chandrayaan-3 in 2023.",
  "The city of Varanasi is considered one of the oldest continuously inhabited cities in the world.",
  "India produces the most milk of any country in the world.",
  "The Indian flag's colors symbolize courage (saffron), peace (white), and prosperity (green).",
  "India has 12 UNESCO World Heritage Sites related solely to natural beauty.",
  "Bollywood, based in Mumbai, produces more films annually than Hollywood.",
  "The word 'shampoo' comes from the Hindi word 'champo', meaning to massage.",
  "India has a floating post office on Dal Lake in Srinagar.",
  "The peacock is India's national bird, admired for its vibrant plumage.",
  "India has the largest number of vegetarians in the world.",
  "Ancient India was a pioneer in surgery — the physician Sushruta performed cataract surgery over 2,000 years ago.",
  "The banyan tree is India's national tree, known for its vast, spreading canopy.",
  "India has more than 2,000 distinct ethnic groups.",
  "The game of Ludo is derived from an ancient Indian game called Pachisi.",
  "India's Meghalaya is one of the wettest places on Earth, receiving immense annual rainfall.",
  "The Indian subcontinent has been home to civilization since the Indus Valley Civilization, over 4,500 years ago.",
  "India has a National Anthem, 'Jana Gana Mana', written by Rabindranath Tagore.",
  "Diwali, the festival of lights, is celebrated by millions across India each year.",
  "India's Thar Desert is one of the most densely populated deserts in the world.",
  "Cotton was first cultivated and spun into cloth in the Indus Valley region of India.",
  "The Indian Space Research Organisation (ISRO) sent a mission to Mars for a fraction of the cost of a Hollywood movie.",
  "India has more than 500 languages and dialects spoken across its states.",
  "The step wells of Gujarat and Rajasthan are stunning examples of ancient Indian architecture.",
  "Bihar's Nalanda University was one of the world's first residential international universities, founded around the 5th century.",
  "India is home to the world's largest mangrove forest, the Sundarbans.",
  "Chai (tea) is a beloved daily ritual for millions of people across India.",
  "Rice has been cultivated in India for thousands of years and remains a staple food.",
  "India has the second-largest standing army in the world.",
  "The game of polo has ancient roots in the northeastern regions of India.",
  "The Great Indian Bustard is one of the heaviest flying birds, found in India's grasslands.",
  "India's classical dance forms, like Bharatanatyam and Kathak, date back thousands of years.",
  "The Konark Sun Temple in Odisha was built to resemble a giant chariot with stone wheels.",
  "India's Rann of Kutch turns into a shimmering white salt desert after the monsoon.",
  "India has 28 states and 8 union territories, each with its own unique culture.",
  "Ayurveda, one of the world's oldest medical systems, originated in India over 3,000 years ago.",
  "Holi, the festival of colors, celebrates the arrival of spring across India.",
  "India's Kerala backwaters are a network of lagoons and lakes famous for houseboats.",
  "The world's tallest statue, the Statue of Unity, stands in Gujarat, India.",
  "India has been growing spices like black pepper and cardamom for thousands of years, earning the nickname 'Spice Land'.",
  "The Himalayas, home to the world's tallest peaks, form India's northern border.",
  "The rupee sign (₹) was designed by an Indian, D. Udaya Kumar, and adopted in 2010.",
  "India's Jaipur is known as the 'Pink City' for its distinctively colored buildings.",
  "Carrom, a popular tabletop game, is thought to have originated in India.",
  "India's Wagah border ceremony features a dramatic daily flag-lowering ritual with Pakistan.",
  "The Indian city of Leh sits at over 11,000 feet, making it one of the highest towns in the world.",
  "India's Ganges River is considered sacred and supports millions of people along its banks.",
  "India has more post offices than banks.",
  "Indian classical music is built on ragas, melodic frameworks passed down for centuries.",
  "The mathematician Brahmagupta first described rules for working with zero and negative numbers in India.",
  "India's Valley of Flowers is a UNESCO site famous for its rare alpine blooms.",
  "India has a rich tradition of storytelling through puppetry, dating back centuries.",
  "The city of Hyderabad is famous for its pearls and centuries-old bazaars.",
  "India's Corbett National Park was the first tiger reserve established in the country.",
  "India has one of the world's largest film industries, producing content in dozens of languages.",
  "The Indian game of Kho Kho is a fast-paced tag sport with deep rural roots.",
  "India's Amber Fort in Rajasthan showcases stunning Rajput and Mughal architecture.",
  "The mathematician Madhava of Sangamagrama laid early groundwork for calculus centuries before Newton and Leibniz.",
  "India's tricolor kite festival, Uttarayan, fills the skies of Gujarat every January.",
  "The Indian city of Mumbai is home to Dharavi, one of Asia's most densely populated areas.",
  "India's Rajasthan hosts the Pushkar Camel Fair, one of the world's largest camel markets.",
  "India produces more postage stamp designs celebrating its culture than most countries.",
  "The Indian mathematician Ramanujan made groundbreaking contributions to number theory with little formal training.",
  "India's Andaman and Nicobar Islands are home to some of the world's few isolated tribes.",
  "The saree, a traditional garment, has been worn in India for over 5,000 years.",
  "India's Ellora Caves feature a temple carved entirely out of a single rock.",
  "The Indian city of Chennai is known as the cultural capital of South India.",
  "India's national game, hockey, has won it multiple Olympic gold medals.",
  "The word 'candy' traces back to the Sanskrit word 'khanda', meaning a piece of sugar.",
  "India's Western Ghats are a UNESCO biodiversity hotspot with thousands of plant species.",
  "The Red Fort in Delhi served as the main residence of Mughal emperors for centuries.",
  "India's classical epics, the Ramayana and Mahabharata, are among the longest poems ever written.",
  "The city of Mysore is famous for its silk, sandalwood, and grand palace.",
  "India's Nagaland celebrates the vibrant Hornbill Festival, showcasing tribal culture.",
  "The Indian dish biryani has regional variations found in nearly every state.",
  "India's Char Dham pilgrimage includes four sacred sites high in the Himalayas.",
  "The rhinoceros of Kaziranga National Park in Assam represent the majority of the world's one-horned rhinos.",
  "India's traditional henna (mehndi) art is used to decorate hands for celebrations.",
  "The Sanskrit language, one of the oldest in the world, has influenced many modern Indian languages.",
  "India's Golden Temple in Amritsar is plated with real gold and welcomes visitors of all faiths.",
  "The Indian city of Kolkata was once the capital of British India.",
  "India's Thar Desert hosts a colorful annual camel and folk festival in Jaisalmer.",
  "India's coastline stretches over 7,500 kilometers, dotted with beaches, ports, and fishing villages.",
] as const;

/** Module-level last-picked index — prevents a fact from showing twice in a row. */
let lastFactIndex = -1;

/** Returns a random fact, never repeating the immediately previous one. */
export function pickFact(): string {
  const n = INDIA_FACTS.length;
  let idx: number;
  do {
    idx = Math.floor(Math.random() * n);
  } while (idx === lastFactIndex && n > 1);
  lastFactIndex = idx;
  return INDIA_FACTS[idx];
}
