// GENERATED BY scripts/wardrobe.mjs FROM scripts/wardrobe/manifest.json.
// Do not edit by hand: edit the manifest and run `node scripts/wardrobe.mjs codegen`.
import type { MascotPose } from "@/components/mascot";

/** Pose art per outfit, relative to MASCOT_BASE. */
export const OUTFIT_POSE_FILES: Record<
  string,
  Partial<Record<MascotPose, string>>
> = {
  "pagdi": {
    wave: "outfits/pagdi/mascot-wave.png",
    cheer: "outfits/pagdi/mascot-cheer.png",
    thumbsup: "outfits/pagdi/mascot-thumbsup.png",
    thinking: "outfits/pagdi/mascot-thinking.png",
    tryagain: "outfits/pagdi/mascot-tryagain.png",
  },
  "station-cap": {
    wave: "outfits/station-cap/mascot-wave.png",
    cheer: "outfits/station-cap/mascot-cheer.png",
    thumbsup: "outfits/station-cap/mascot-thumbsup.png",
    thinking: "outfits/station-cap/mascot-thinking.png",
    tryagain: "outfits/station-cap/mascot-tryagain.png",
  },
};

/** The accessory alone, transparent, in the same frame as every pose. */
export const ACCESSORY_OVERLAY_FILES: Record<
  string,
  Partial<Record<MascotPose, string>>
> = {
  "pagdi": {
    wave: "outfits/pagdi/overlay-wave.png",
    cheer: "outfits/pagdi/overlay-cheer.png",
    thumbsup: "outfits/pagdi/overlay-thumbsup.png",
    thinking: "outfits/pagdi/overlay-thinking.png",
    tryagain: "outfits/pagdi/overlay-tryagain.png",
  },
  "station-cap": {
    wave: "outfits/station-cap/overlay-wave.png",
    cheer: "outfits/station-cap/overlay-cheer.png",
    thumbsup: "outfits/station-cap/overlay-thumbsup.png",
    thinking: "outfits/station-cap/overlay-thinking.png",
    tryagain: "outfits/station-cap/overlay-tryagain.png",
  },
};
