// GENERATED BY scripts/wardrobe.mjs FROM scripts/wardrobe/manifest.json.
// Do not edit by hand: edit the manifest and run `node scripts/wardrobe.mjs codegen`.
/** The Station Master's rack; the Tailor sells everything else. */
export const STATION_IDS: ReadonlySet<string> = new Set(["station-cap"]);
