export {
  openai,
  detectAudioFormat,
  convertToWav,
  ensureCompatibleFormat,
  type AudioFormat,
  voiceChat,
  voiceChatStream,
  textToSpeech,
  textToSpeechElevenLabs,
  getElevenLabsQuota,
  type ElevenLabsQuota,
  getElevenLabsUsageStats,
  type ElevenLabsUsageStats,
  textToSpeechStream,
  speechToText,
  type SpeechToTextOptions,
  speechToTextStream,
} from "./client";
