/**
 * Regenerate lib/emergency/src/films.ts from what is actually on disk.
 *
 *   pnpm --filter @workspace/scripts run scan-emergency-films
 *
 * THE WHOLE WORKFLOW THIS EXISTS TO SUPPORT. The owner generates a 9:16 film
 * per zone, compresses it, drops it in, and runs this. Nothing else. No code
 * change, no list to keep in step by hand, and no way for the manifest to
 * disagree with the directory.
 *
 * WHY THE MANIFEST IS COMPILED IN RATHER THAN PROBED AT RUNTIME is explained in
 * films.ts and is the reason this script exists at all: the client must know a
 * film is missing BEFORE it flashes EMERGENCY across the screen, because taking
 * an interruption back is worse than never firing it.
 *
 * DROP THE FILE HERE:
 *   artifacts/gujarati-coach/public/emergency/j1z<N>.mp4
 *
 * COMPRESS IT FIRST. A 10-second 1080x1920 export runs about 13MB, and six of
 * those is 77MB in git forever. At 720x1280 the same clip is about 2MB with no
 * visible loss on a phone, measured 2026-08-24:
 *
 *   ffmpeg -i INPUT.mp4 -vf "scale=720:1280:flags=lanczos" \
 *     -c:v libx264 -profile:v main -crf 27 -preset slow -pix_fmt yuv420p \
 *     -movflags +faststart -c:a aac -b:a 64k artifacts/gujarati-coach/public/emergency/j1z2.mp4
 *
 * This script REFUSES a file over the size ceiling rather than quietly
 * committing it, because nobody notices a repository getting heavier until it
 * is too late to take back.
 */
import { readdirSync, statSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { EMERGENCY_FILMS_EXPECTED, emergencyFilmId } from "@workspace/emergency";

const HERE = dirname(fileURLToPath(import.meta.url));
const FILMS = resolve(HERE, "../../artifacts/gujarati-coach/public/emergency");
const OUT = resolve(HERE, "../../lib/emergency/src/films.ts");

/** Refuse anything above this. See the ffmpeg recipe in the header. */
const MAX_BYTES = 4 * 1024 * 1024;

function main(): void {
  if (!existsSync(FILMS)) {
    console.error(`No films directory at ${FILMS}. Create it and drop j1z1.mp4 in.`);
    process.exit(1);
  }

  const found: { zone: number; bytes: number }[] = [];
  const oversized: string[] = [];
  const unexpected: string[] = [];

  for (const name of readdirSync(FILMS).sort()) {
    if (name.startsWith(".")) continue;
    const m = /^j1z([1-9]\d*)\.mp4$/.exec(name);
    if (!m) {
      unexpected.push(name);
      continue;
    }
    const zone = Number(m[1]);
    if (zone < 1 || zone > EMERGENCY_FILMS_EXPECTED) {
      unexpected.push(`${name} (zone ${zone} is outside 1..${EMERGENCY_FILMS_EXPECTED})`);
      continue;
    }
    const bytes = statSync(resolve(FILMS, name)).size;
    if (bytes > MAX_BYTES) {
      oversized.push(`${name} is ${(bytes / 1048576).toFixed(1)}MB`);
      continue;
    }
    found.push({ zone, bytes });
  }

  // LOUD ABOUT ANYTHING IT IGNORED. A file the owner dropped in that this
  // script silently skipped is the worst outcome available: they would have
  // every reason to believe the zone was covered.
  for (const u of unexpected) {
    console.warn(
      `IGNORED ${u}. Films must be named ${emergencyFilmId(1, 2)}.mp4 and so on.`,
    );
  }
  if (oversized.length > 0) {
    console.error(
      `REFUSED, over the ${MAX_BYTES / 1048576}MB ceiling:\n  ` +
        oversized.join("\n  ") +
        "\nCompress with the ffmpeg recipe at the top of this script, then re-run.",
    );
    process.exit(1);
  }

  found.sort((a, b) => a.zone - b.zone);
  const zones = found.map((f) => f.zone);
  const total = found.reduce((n, f) => n + f.bytes, 0);

  const body = `/**
 * WHICH ZONES ACTUALLY HAVE A FILM.
 *
 * GENERATED by scripts/src/scanEmergencyFilms.ts. Do not hand-edit; drop the
 * .mp4 into artifacts/gujarati-coach/public/emergency/ and run:
 *
 *   pnpm --filter @workspace/scripts run scan-emergency-films
 *
 * WHY A COMMITTED MANIFEST AND NOT A RUNTIME PROBE. The Emergency opens by
 * flashing the word EMERGENCY across the whole screen to interrupt the learner.
 * If the film for that zone turns out to be missing, the only honest thing left
 * to do is take the interruption away again, and an interruption that appears
 * and then apologises is worse than one that never fired. So the client has to
 * know BEFORE the alarm, which means knowing without a network round trip,
 * which means a value compiled in.
 *
 * A 404 handler would have been less code and would have shipped the exact bug
 * this file exists to prevent.
 *
 * The same manifest serves web, iOS and Android, so a film that exists for one
 * platform and not another is not a state this app can get into.
 */

/** Zones of journey 1 with a film on disk, ascending. */
export const EMERGENCY_FILM_ZONES: readonly number[] = [${zones.join(", ")}];

/**
 * How many zones journey 1 has. A zone with no film simply has no Emergency,
 * silently, which is the designed fallback rather than a gap to apologise for.
 */
export const EMERGENCY_FILMS_EXPECTED = ${EMERGENCY_FILMS_EXPECTED};
`;
  writeFileSync(OUT, body);

  const missing = Array.from({ length: EMERGENCY_FILMS_EXPECTED }, (_, i) => i + 1).filter(
    (z) => !zones.includes(z),
  );
  console.log(
    `emergency films: ${zones.length}/${EMERGENCY_FILMS_EXPECTED} zones, ` +
      `${(total / 1048576).toFixed(1)}MB -> ${OUT}`,
  );
  if (missing.length > 0) {
    // A warning, never an error. A partial set is the expected state while the
    // films are still being made, and the zones without one just have no
    // Emergency.
    console.warn(
      `WARNING: no film yet for zone(s) ${missing.join(", ")}. ` +
        `Those zones will SKIP the Emergency entirely, which is the intended fallback.`,
    );
  }
}

main();
