// THE 3D BIRD: which one the app shows, and where its files are.
//
// WHEN THE DESIGNER'S BOLO ARRIVES, THIS IS THE FILE THAT CHANGES. Drop her
// file in as assets/bolo3d/bolo.glb, run the audit
// (node scripts/bolo3d/audit.mjs artifacts/bolo-mobile/assets/bolo3d/bolo.glb),
// then point CHARACTER at BOLO_RIG and her file. Nothing that renders a
// <Bolo3D> needs to know: every screen speaks the contract's clip, mood and
// socket names, never the stand-in's.
//
// THE STAND-IN IS NOT BOLO. "Ducky the duck" by BlueMesh (CC-BY-4.0, credited
// on the lab screen), supplied by the owner on 2026-09-16 so the runtime could
// be built and seen before the real bird exists.

import { Asset } from 'expo-asset';
import {
  STANDIN_DUCKY_RIG,
  mouthTrackFromDuration,
  type MouthKey,
  type RigProfile,
  type Socket,
} from '@workspace/bolo-character';

export { BOLO3D_IN_SCREENS, BOLO3D_LAB_ENABLED } from './bolo3dFlag';

export const CHARACTER: { rig: RigProfile; model: number } = {
  rig: STANDIN_DUCKY_RIG,
  model: require('../assets/bolo3d/standin-ducky.glb'),
};

// Generated by lib/bolo-stage/build.mjs. Never edit it by hand.
const STAGE_PAGE: number = require('../assets/bolo3d/stage.html');


export type StageAssets = {
  /** file:// URL of the stage page. */
  page: string;
  /** file:// URL of the model, read by the page with XHR. */
  model: string;
  /**
   * The directory iOS's WKWebView may read from. The page and the model must
   * both sit inside it, or the model read is refused.
   */
  readAccess: string;
};

const cache = new Map<number, Promise<StageAssets>>();

/**
 * Both files as local file:// URLs. In development expo-asset downloads them
 * from Metro into the cache directory; in a release build it resolves the
 * copies bundled with the app. Either way they end up side by side, and the
 * WebView is granted the directory they share.
 */
export function loadStageAssets(model: number = CHARACTER.model): Promise<StageAssets> {
  let pending = cache.get(model);
  if (!pending) {
    pending = (async () => {
      const [page, glb] = await Promise.all([
        Asset.fromModule(STAGE_PAGE).downloadAsync(),
        Asset.fromModule(model).downloadAsync(),
      ]);
      const pageUri = page.localUri ?? page.uri;
      const modelUri = glb.localUri ?? glb.uri;
      return { page: pageUri, model: modelUri, readAccess: sharedDirectory(pageUri, modelUri) };
    })();
    // A failed download must not be cached forever: the next mount retries.
    pending.catch(() => cache.delete(model));
    cache.set(model, pending);
  }
  return pending;
}

/**
 * THE CATALOGUE IN 3D: which piece the 3D bird wears for each shop item. Every
 * entry is a STAND-IN today (lib/bolo-stage/src/wardrobe.ts), the right kind of
 * hat rather than the delivered art, and each is replaced by a real 3D piece
 * when those are made. An item with no entry leaves her bare-headed in 3D, and
 * never breaks the 2D bird, which still reads the catalogue's own art.
 */
export const WARDROBE_3D: Readonly<Record<string, { socket: Socket; piece: string }>> = {
  pagdi: { socket: 'attach_head', piece: 'standin-pagdi' },
  'station-cap': { socket: 'attach_head', piece: 'standin-harbour-cap' },
  'pink-beanie2': { socket: 'attach_head', piece: 'standin-beanie' },
};

/** What the 3D bird wears for an equipped (or previewed) garment and accessory. */
export function wear3d(garment?: string | null, accessory?: string | null): Partial<Record<Socket, string | null>> {
  const wear: Partial<Record<Socket, string | null>> = { attach_head: null, attach_body: null };
  for (const id of [garment, accessory]) {
    const mapped = id ? WARDROBE_3D[id] : undefined;
    if (mapped) wear[mapped.socket] = mapped.piece;
  }
  return wear;
}

/**
 * A talking beak for audio that arrives with no timings: chat's streamed
 * replies and the lesson's phrase audio today. A syllable rhythm long enough
 * for any reply; the caller silences it the moment the audio stops, so she
 * never mouths past the end. Replaced per clip by the real per-letter track
 * once the server returns ElevenLabs' timings (docs/bolo3d.md, Next).
 */
let chatter: MouthKey[] | null = null;
export function chatterTrack(): MouthKey[] {
  chatter ??= mouthTrackFromDuration(90);
  return chatter;
}

/** The deepest directory containing both URLs, with a trailing slash. */
export function sharedDirectory(a: string, b: string): string {
  const left = a.split('/');
  const right = b.split('/');
  const shared: string[] = [];
  for (let i = 0; i < Math.min(left.length, right.length) - 1; i++) {
    if (left[i] !== right[i]) break;
    shared.push(left[i]);
  }
  return `${shared.join('/')}/`;
}
