// GENERATED BY scripts/wardrobe.mjs FROM scripts/wardrobe/manifest.json.
// Do not edit by hand: edit the manifest and run `node scripts/wardrobe.mjs codegen`.
// Metro needs literal require() paths, which is why this file exists at all:
// the map cannot be built from a loop at runtime. Only items whose pose
// files are actually installed appear; a pose a client has not shipped
// falls back to canonical Bolo rather than blanking her (mascotSource).
import type { MascotPose } from '@/components/Mascot';

export const OUTFIT_POSE_SOURCES: Record<
  string,
  Partial<Record<MascotPose, number>>
> = {
  pagdi: {
    wave: require('../assets/images/mascot/outfits/pagdi/mascot-wave.png'),
    cheer: require('../assets/images/mascot/outfits/pagdi/mascot-cheer.png'),
    thumbsup: require('../assets/images/mascot/outfits/pagdi/mascot-thumbsup.png'),
    thinking: require('../assets/images/mascot/outfits/pagdi/mascot-thinking.png'),
    tryagain: require('../assets/images/mascot/outfits/pagdi/mascot-tryagain.png'),
  },
  'station-cap': {
    wave: require('../assets/images/mascot/outfits/station-cap/mascot-wave.png'),
    cheer: require('../assets/images/mascot/outfits/station-cap/mascot-cheer.png'),
    thumbsup: require('../assets/images/mascot/outfits/station-cap/mascot-thumbsup.png'),
    thinking: require('../assets/images/mascot/outfits/station-cap/mascot-thinking.png'),
    tryagain: require('../assets/images/mascot/outfits/station-cap/mascot-tryagain.png'),
  },
  'pink-beanie2': {
    wave: require('../assets/images/mascot/outfits/pink-beanie2/mascot-wave.png'),
    cheer: require('../assets/images/mascot/outfits/pink-beanie2/mascot-cheer.png'),
    thumbsup: require('../assets/images/mascot/outfits/pink-beanie2/mascot-thumbsup.png'),
    thinking: require('../assets/images/mascot/outfits/pink-beanie2/mascot-thinking.png'),
    tryagain: require('../assets/images/mascot/outfits/pink-beanie2/mascot-tryagain.png'),
  },
  'puffer-vest': {
    wave: require('../assets/images/mascot/outfits/puffer-vest/mascot-wave.png'),
    cheer: require('../assets/images/mascot/outfits/puffer-vest/mascot-cheer.png'),
    thumbsup: require('../assets/images/mascot/outfits/puffer-vest/mascot-thumbsup.png'),
    thinking: require('../assets/images/mascot/outfits/puffer-vest/mascot-thinking.png'),
    tryagain: require('../assets/images/mascot/outfits/puffer-vest/mascot-tryagain.png'),
  },
};

export const ACCESSORY_OVERLAY_SOURCES: Record<
  string,
  Partial<Record<MascotPose, number>>
> = {
  pagdi: {
    wave: require('../assets/images/mascot/outfits/pagdi/overlay-wave.png'),
    cheer: require('../assets/images/mascot/outfits/pagdi/overlay-cheer.png'),
    thumbsup: require('../assets/images/mascot/outfits/pagdi/overlay-thumbsup.png'),
    thinking: require('../assets/images/mascot/outfits/pagdi/overlay-thinking.png'),
    tryagain: require('../assets/images/mascot/outfits/pagdi/overlay-tryagain.png'),
  },
  'station-cap': {
    wave: require('../assets/images/mascot/outfits/station-cap/overlay-wave.png'),
    cheer: require('../assets/images/mascot/outfits/station-cap/overlay-cheer.png'),
    thumbsup: require('../assets/images/mascot/outfits/station-cap/overlay-thumbsup.png'),
    thinking: require('../assets/images/mascot/outfits/station-cap/overlay-thinking.png'),
    tryagain: require('../assets/images/mascot/outfits/station-cap/overlay-tryagain.png'),
  },
  'pink-beanie2': {
    wave: require('../assets/images/mascot/outfits/pink-beanie2/overlay-wave.png'),
    cheer: require('../assets/images/mascot/outfits/pink-beanie2/overlay-cheer.png'),
    thumbsup: require('../assets/images/mascot/outfits/pink-beanie2/overlay-thumbsup.png'),
    thinking: require('../assets/images/mascot/outfits/pink-beanie2/overlay-thinking.png'),
    tryagain: require('../assets/images/mascot/outfits/pink-beanie2/overlay-tryagain.png'),
  },
};
