// GENERATED BY scripts/wardrobe.mjs FROM scripts/wardrobe/manifest.json.
// Do not edit by hand: edit the manifest and run `node scripts/wardrobe.mjs codegen`.
// Metro needs literal require() paths, which is why this file exists at all:
// the map cannot be built from a loop at runtime. Only items whose pose
// files are actually installed appear; a pose a client has not shipped
// falls back to canonical Bolo rather than blanking her (mascotSource).
import type { MascotPose } from '@/components/Mascot';

export const OUTFIT_POSE_SOURCES: Record<
  string,
  Partial<Record<MascotPose, number>>
> = {
  navratri: {
    wave: require('../assets/images/mascot/outfits/navratri/mascot-wave.png'),
    cheer: require('../assets/images/mascot/outfits/navratri/mascot-cheer.png'),
    thumbsup: require('../assets/images/mascot/outfits/navratri/mascot-thumbsup.png'),
    thinking: require('../assets/images/mascot/outfits/navratri/mascot-thinking.png'),
    tryagain: require('../assets/images/mascot/outfits/navratri/mascot-tryagain.png'),
  },
  kediyu: {
    wave: require('../assets/images/mascot/outfits/kediyu/mascot-wave.png'),
    cheer: require('../assets/images/mascot/outfits/kediyu/mascot-cheer.png'),
    thumbsup: require('../assets/images/mascot/outfits/kediyu/mascot-thumbsup.png'),
    thinking: require('../assets/images/mascot/outfits/kediyu/mascot-thinking.png'),
    tryagain: require('../assets/images/mascot/outfits/kediyu/mascot-tryagain.png'),
  },
  anarkali: {
    wave: require('../assets/images/mascot/outfits/anarkali/mascot-wave.png'),
    cheer: require('../assets/images/mascot/outfits/anarkali/mascot-cheer.png'),
    thumbsup: require('../assets/images/mascot/outfits/anarkali/mascot-thumbsup.png'),
    thinking: require('../assets/images/mascot/outfits/anarkali/mascot-thinking.png'),
    tryagain: require('../assets/images/mascot/outfits/anarkali/mascot-tryagain.png'),
  },
  kurta: {
    wave: require('../assets/images/mascot/outfits/kurta/mascot-wave.png'),
    cheer: require('../assets/images/mascot/outfits/kurta/mascot-cheer.png'),
    thumbsup: require('../assets/images/mascot/outfits/kurta/mascot-thumbsup.png'),
    thinking: require('../assets/images/mascot/outfits/kurta/mascot-thinking.png'),
    tryagain: require('../assets/images/mascot/outfits/kurta/mascot-tryagain.png'),
  },
  sherwani: {
    wave: require('../assets/images/mascot/outfits/sherwani/mascot-wave.png'),
    cheer: require('../assets/images/mascot/outfits/sherwani/mascot-cheer.png'),
    thumbsup: require('../assets/images/mascot/outfits/sherwani/mascot-thumbsup.png'),
    thinking: require('../assets/images/mascot/outfits/sherwani/mascot-thinking.png'),
    tryagain: require('../assets/images/mascot/outfits/sherwani/mascot-tryagain.png'),
  },
  saree: {
    wave: require('../assets/images/mascot/outfits/saree/mascot-wave.png'),
    cheer: require('../assets/images/mascot/outfits/saree/mascot-cheer.png'),
    thumbsup: require('../assets/images/mascot/outfits/saree/mascot-thumbsup.png'),
    thinking: require('../assets/images/mascot/outfits/saree/mascot-thinking.png'),
    tryagain: require('../assets/images/mascot/outfits/saree/mascot-tryagain.png'),
  },
  pagdi: {
    wave: require('../assets/images/mascot/outfits/pagdi/mascot-wave.png'),
    cheer: require('../assets/images/mascot/outfits/pagdi/mascot-cheer.png'),
    thumbsup: require('../assets/images/mascot/outfits/pagdi/mascot-thumbsup.png'),
    thinking: require('../assets/images/mascot/outfits/pagdi/mascot-thinking.png'),
    tryagain: require('../assets/images/mascot/outfits/pagdi/mascot-tryagain.png'),
  },
  'station-cap': {
    wave: require('../assets/images/mascot/outfits/station-cap/mascot-wave.png'),
    cheer: require('../assets/images/mascot/outfits/station-cap/mascot-cheer.png'),
    thumbsup: require('../assets/images/mascot/outfits/station-cap/mascot-thumbsup.png'),
    thinking: require('../assets/images/mascot/outfits/station-cap/mascot-thinking.png'),
    tryagain: require('../assets/images/mascot/outfits/station-cap/mascot-tryagain.png'),
  },
};

export const ACCESSORY_OVERLAY_SOURCES: Record<
  string,
  Partial<Record<MascotPose, number>>
> = {
  pagdi: {
    wave: require('../assets/images/mascot/outfits/pagdi/overlay-wave.png'),
    cheer: require('../assets/images/mascot/outfits/pagdi/overlay-cheer.png'),
    thumbsup: require('../assets/images/mascot/outfits/pagdi/overlay-thumbsup.png'),
    thinking: require('../assets/images/mascot/outfits/pagdi/overlay-thinking.png'),
    tryagain: require('../assets/images/mascot/outfits/pagdi/overlay-tryagain.png'),
  },
  'station-cap': {
    wave: require('../assets/images/mascot/outfits/station-cap/overlay-wave.png'),
    cheer: require('../assets/images/mascot/outfits/station-cap/overlay-cheer.png'),
    thumbsup: require('../assets/images/mascot/outfits/station-cap/overlay-thumbsup.png'),
    thinking: require('../assets/images/mascot/outfits/station-cap/overlay-thinking.png'),
    tryagain: require('../assets/images/mascot/outfits/station-cap/overlay-tryagain.png'),
  },
};
