// GENERATED BY scripts/wardrobe.mjs FROM scripts/wardrobe/manifest.json.
// Do not edit by hand: edit the manifest and run `node scripts/wardrobe.mjs codegen`.

import { ACCESSORY_COST, OUTFIT_COST, PREMIUM_OUTFIT_COST } from "./tokenEconomy";

export const OUTFIT_IDS = [
  "navratri",
  "kediyu",
  "anarkali",
  "kurta",
  "sherwani",
  "saree",
  "pagdi",
  "station-cap",
] as const;
export type OutfitId = (typeof OUTFIT_IDS)[number];

/** A garment redresses the whole bird; an accessory adds one thing to her. */
export type OutfitKind = "garment" | "accessory";
/** How the shop should crop this item's preview: the whole bird, or her head. */
export type OutfitPreview = "full" | "head";
/** Which Bazaar door stocks it. */
export type OutfitShopDoor = "tailor" | "station";

export type OutfitCatalogEntry = {
  id: OutfitId;
  name: string;
  tagline: string;
  cost: number;
  kind: OutfitKind;
  preview: OutfitPreview;
  shop: OutfitShopDoor;
};

export const OUTFIT_CATALOG: readonly OutfitCatalogEntry[] = [
  {
    id: "navratri",
    name: "Navratri chaniya choli",
    tagline: "Nine nights of dancing, mirrors and all.",
    cost: OUTFIT_COST,
    kind: "garment",
    preview: "full",
    shop: "tailor",
  },
  {
    id: "kediyu",
    name: "Navratri kediyu",
    tagline: "Mirror-work cotton, cut for nine nights of garba.",
    cost: OUTFIT_COST,
    kind: "garment",
    preview: "full",
    shop: "tailor",
  },
  {
    id: "anarkali",
    name: "Diwali anarkali",
    tagline: "Magenta and gold, and it spins beautifully.",
    cost: OUTFIT_COST,
    kind: "garment",
    preview: "full",
    shop: "tailor",
  },
  {
    id: "kurta",
    name: "Diwali kurta",
    tagline: "Saffron cotton, a gold placket, churidar to match.",
    cost: OUTFIT_COST,
    kind: "garment",
    preview: "full",
    shop: "tailor",
  },
  {
    id: "sherwani",
    name: "Wedding sherwani",
    tagline: "Cream brocade and gold buttons. Baraat-ready.",
    cost: PREMIUM_OUTFIT_COST,
    kind: "garment",
    preview: "full",
    shop: "tailor",
  },
  {
    id: "saree",
    name: "Banarasi saree",
    tagline: "Crimson silk with a whole river of gold zari.",
    cost: PREMIUM_OUTFIT_COST,
    kind: "garment",
    preview: "full",
    shop: "tailor",
  },
  {
    id: "pagdi",
    name: "Marigold pagdi",
    tagline: "Marigold silk, gold zari and one peacock feather.",
    cost: ACCESSORY_COST,
    kind: "accessory",
    preview: "head",
    shop: "tailor",
  },
  {
    id: "station-cap",
    name: "Station master's cap",
    tagline: "Navy and red, with a little brass engine on the badge.",
    cost: ACCESSORY_COST,
    kind: "accessory",
    preview: "head",
    shop: "station",
  },
];
