// GENERATED BY scripts/wardrobe.mjs FROM scripts/wardrobe/manifest.json.
// Do not edit by hand: edit the manifest and run `node scripts/wardrobe.mjs codegen`.

import { ACCESSORY_COST } from "./tokenEconomy";

export const OUTFIT_IDS = [
  "pagdi",
  "station-cap",
  "pink-beanie2",
] as const;
export type OutfitId = (typeof OUTFIT_IDS)[number];

/**
 * Which slot a piece occupies.
 *
 *   garment    the whole body, top and bottom at once (a saree, a sherwani)
 *   top        her upper half only, worn with a bottom
 *   bottom     her lower half only; NEVER worn without a top
 *   accessory  her head
 *
 * "garment" is the original whole-body kind and keeps its name so the six
 * pieces that predate two-part clothing need no migration.
 */
export type OutfitKind = "garment" | "top" | "bottom" | "accessory";
/** How the shop should crop this item's preview: the whole bird, or her head. */
export type OutfitPreview = "full" | "head";
/** Which Bazaar door stocks it. */
export type OutfitShopDoor = "tailor" | "station";

export type OutfitCatalogEntry = {
  id: OutfitId;
  name: string;
  tagline: string;
  cost: number;
  kind: OutfitKind;
  preview: OutfitPreview;
  shop: OutfitShopDoor;
};

export const OUTFIT_CATALOG: readonly OutfitCatalogEntry[] = [
  {
    id: "pagdi",
    name: "Marigold pagdi",
    tagline: "Marigold silk, gold zari and one peacock feather.",
    cost: ACCESSORY_COST,
    kind: "accessory",
    preview: "head",
    shop: "tailor",
  },
  {
    id: "station-cap",
    name: "Station master's cap",
    tagline: "Navy and red, with a little brass engine on the badge.",
    cost: ACCESSORY_COST,
    kind: "accessory",
    preview: "head",
    shop: "station",
  },
  {
    id: "pink-beanie2",
    name: "Pink Knit Beanie",
    tagline: "",
    cost: ACCESSORY_COST,
    kind: "accessory",
    preview: "head",
    shop: "tailor",
  },
];
