#!/usr/bin/env node
// Bundle the stage into ONE self-contained HTML file for the phone's WebView.
//
// One file, because a WebView loading file:// URLs is the least forgiving host
// there is: no module loader, no second request that can fail on its own. The
// model is the only other file, and it is read with XHR (see model.ts).
//
//   pnpm --filter @workspace/bolo-stage run build    writes the file
//   pnpm --filter @workspace/bolo-stage run check    fails if it is stale
//
// The output is committed, because EAS builds from git and Metro bundles it as
// an asset; it is never edited by hand.

import { build } from 'esbuild';
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, '..', '..');
const OUTPUT = join(repo, 'artifacts/bolo-mobile/assets/bolo3d/stage.html');
const check = process.argv.includes('--check');

const result = await build({
  entryPoints: [join(here, 'src/page.ts')],
  bundle: true,
  minify: true,
  format: 'iife',
  // Expo SDK 54 supports iOS 15.1 and up; WKWebView there is Safari 15.
  target: ['es2020', 'safari15', 'chrome90'],
  write: false,
  // three.js is MIT: its licence notice travels with it, at the end.
  legalComments: 'eof',
  conditions: ['workspace'],
  logLevel: 'warning',
});
const js = result.outputFiles[0].text.replace(/<\/script/gi, '<\\/script');
const bundle = createHash('sha256').update(js).digest('hex').slice(0, 16);

const html = `<!doctype html>
<!-- GENERATED by lib/bolo-stage/build.mjs. Do not edit: change lib/bolo-stage/src and rebuild. bundle ${bundle} -->
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><style>html,body{margin:0;width:100%;height:100%;overflow:hidden;background:transparent;-webkit-user-select:none;user-select:none;-webkit-touch-callout:none;-webkit-tap-highlight-color:transparent}canvas{display:block;width:100%;height:100%;touch-action:pan-y;outline:none}</style></head><body><canvas id="stage"></canvas><script>${js}</script></body></html>
`;

const where = relative(repo, OUTPUT);
if (check) {
  const current = existsSync(OUTPUT) ? readFileSync(OUTPUT, 'utf8') : '';
  if (current !== html) {
    console.error(`${where} is stale: run pnpm --filter @workspace/bolo-stage run build`);
    process.exit(1);
  }
  console.log(`${where} is current (bundle ${bundle})`);
} else {
  mkdirSync(dirname(OUTPUT), { recursive: true });
  writeFileSync(OUTPUT, html);
  console.log(`wrote ${where}: ${(html.length / 1024).toFixed(0)} KB, bundle ${bundle}`);
}
