/**
 * WHICH ZONES ACTUALLY HAVE A FILM.
 *
 * GENERATED by scripts/src/scanEmergencyFilms.ts. Do not hand-edit; drop the
 * .mp4 into artifacts/gujarati-coach/public/emergency/ and run:
 *
 *   pnpm --filter @workspace/scripts run scan-emergency-films
 *
 * WHY A COMMITTED MANIFEST AND NOT A RUNTIME PROBE. The Emergency opens by
 * flashing the word EMERGENCY across the whole screen to interrupt the learner.
 * If the film for that zone turns out to be missing, the only honest thing left
 * to do is take the interruption away again, and an interruption that appears
 * and then apologises is worse than one that never fired. So the client has to
 * know BEFORE the alarm, which means knowing without a network round trip,
 * which means a value compiled in.
 *
 * A 404 handler would have been less code and would have shipped the exact bug
 * this file exists to prevent.
 *
 * The same manifest serves web, iOS and Android, so a film that exists for one
 * platform and not another is not a state this app can get into.
 */

/** Zones of journey 1 with a film on disk, ascending. */
export const EMERGENCY_FILM_ZONES: readonly number[] = [1, 2, 3, 4];

/**
 * How many zones journey 1 has. A zone with no film simply has no Emergency,
 * silently, which is the designed fallback rather than a gap to apologise for.
 */
export const EMERGENCY_FILMS_EXPECTED = 6;
