#!/usr/bin/env node
// THE WARDROBE COMMAND (build 25). One manifest, everything generated.
//
// Adding a piece of Bolo clothing used to be nine manual steps across three
// artifacts: source art, a recut, knob tuning, review sheets in /tmp, ten
// pose files, and FOUR hand-edited registries (the recipe table inside the
// generator, the server catalogue, mobile's literal require() map, and the
// shop ids on both clients). This command reduces it to: add an entry to
// scripts/wardrobe/manifest.json, then
//
//   node scripts/wardrobe.mjs gen <id>        composite + review sheet into docs/garment-review/<id>/
//   node scripts/wardrobe.mjs install <id>    write the pose files AND regenerate every registry
//   node scripts/wardrobe.mjs codegen         regenerate the registries alone
//   node scripts/wardrobe.mjs check           parity: manifest vs catalogue vs shipped art, both clients
//   node scripts/wardrobe.mjs montage         one contact sheet of every piece in every pose
//
// The compositing engines are unchanged: gen-mascot-outfits.mjs (cloth over
// the belly, wings restacked in front) and gen-mascot-accessories.mjs
// (transparent overlays with derived eye clearance). This file only feeds
// them their recipes and owns the registries they used to share with humans.
import { execFileSync } from "node:child_process";
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const MANIFEST_PATH = join(ROOT, "scripts/wardrobe/manifest.json");
const WEB_OUT = join(ROOT, "artifacts/gujarati-coach/public/mascot/outfits");
const MOBILE_OUT = join(ROOT, "artifacts/bolo-mobile/assets/images/mascot/outfits");
const REVIEW_DIR = join(ROOT, "docs/garment-review");
const POSES = ["wave", "cheer", "thumbsup", "thinking", "tryagain"];

/**
 * The sprite frame every installed pose must match.
 *
 * IT GREW IN BUILD 26, from 1024 square, so a plume or a tassel has sky to
 * draw into. `check` was left asserting the square and called every correctly
 * generated sprite a problem, which is worse than not checking: 17 red lines
 * that all mean "this file is fine" train you to skip the output. Found in
 * build 27 by a Publish button that runs `check` as its last step.
 * The twins are MASCOT_SKY_PCT (web mascot.tsx) and MASCOT_SPRITE_H (mobile
 * Mascot.tsx); all three must agree or accessories slide off her head.
 */
const SPRITE_W = 1024;
const SPRITE_H = 1200;

const GEN_HEADER = `// GENERATED BY scripts/wardrobe.mjs FROM scripts/wardrobe/manifest.json.
// Do not edit by hand: edit the manifest and run \`node scripts/wardrobe.mjs codegen\`.
`;

function manifest() {
  return JSON.parse(readFileSync(MANIFEST_PATH, "utf8"));
}
function item(id) {
  const it = manifest().items.find((i) => i.id === id);
  if (!it) {
    console.error(`no manifest entry for "${id}" — add it to scripts/wardrobe/manifest.json first`);
    process.exit(1);
  }
  return it;
}

// ---------------------------------------------------------------------------
// gen / install: feed the compositing engines their recorded recipes.
// ---------------------------------------------------------------------------
function gen(id, { install = false } = {}) {
  const it = item(id);
  if (!it.art) {
    console.error(`"${id}" has no source art in the repo (${it.note ?? "no note"}); nothing to generate.`);
    process.exit(1);
  }
  const r = it.recipe ?? {};
  let sheet;
  // A top and a bottom are cloth on her body, so they go through the OUTFIT
  // generator exactly as a whole-body garment does; only the head slot uses the
  // accessory pipeline. Getting this wrong sends a shirt through the eye
  // clearance loop and seats it on her forehead.
  if (it.kind === "garment" || it.kind === "top" || it.kind === "bottom") {
    const args = ["scripts/gen-mascot-outfits.mjs", "--art", it.art, "--id", id];
    for (const k of ["wfrac", "dy", "squash", "freefrac"]) {
      if (r[k] !== undefined) args.push(`--${k}`, String(r[k]));
    }
    if (install) args.push("--install");
    execFileSync("node", args, { cwd: ROOT, stdio: "inherit" });
    sheet = `/tmp/mascot-dress/${id}/${id}-all5.png`;
  } else {
    const args = ["scripts/gen-mascot-accessories.mjs", "--id", id];
    for (const k of ["fudge", "margin"]) {
      if (r[k] !== undefined) args.push(`--${k}`, String(r[k]));
    }
    if (install) args.push("--install");
    execFileSync("node", args, { cwd: ROOT, stdio: "inherit" });
    sheet = `/tmp/mascot-acc/${id}/${id}-faces.png`;
  }
  // The review sheet survives the session, in the folder the sherwani rounds
  // already proved the worth of.
  if (existsSync(sheet)) {
    const out = join(REVIEW_DIR, id);
    mkdirSync(out, { recursive: true });
    const stamp = new Date().toISOString().slice(0, 10);
    copyFileSync(sheet, join(out, `${id}-all5-${stamp}.png`));
    console.log(`review sheet → docs/garment-review/${id}/${id}-all5-${stamp}.png`);
  }
}

// ---------------------------------------------------------------------------
// codegen: the registries nobody hand-edits any more.
// ---------------------------------------------------------------------------
const COST_CONST = {
  standard: "OUTFIT_COST",
  premium: "PREMIUM_OUTFIT_COST",
  accessory: "ACCESSORY_COST",
};

/**
 * What an item costs in Chai, as the EXPRESSION the catalogue should emit.
 *
 * `costBand` was the only lever until build 27: three shared constants, so
 * pricing a piece meant repricing every piece in its band. The owner asked to
 * set a price per item ("make sure I can set the price in chai as well"), so a
 * numeric `cost` on the item now wins and the band stays as the default.
 *
 * The band is deliberately NOT removed. Most items should move together when
 * the economy is retuned, and an item with no `cost` still does. A number here
 * is an opt OUT of that, which is why it reads as a literal in the generated
 * file rather than as a constant.
 */
function costExpression(it) {
  if (it.cost === undefined || it.cost === null) {
    const band = COST_CONST[it.costBand];
    if (!band) throw new Error(`${it.id}: unknown costBand "${it.costBand}" and no numeric cost`);
    return band;
  }
  if (!Number.isInteger(it.cost) || it.cost < 0) {
    throw new Error(`${it.id}: cost must be a whole number of Chai, got ${JSON.stringify(it.cost)}`);
  }
  return String(it.cost);
}

function genServerCatalog(m) {
  const lines = [];
  lines.push(GEN_HEADER);
  // Only import the band constants still in use: an all-numeric manifest would
  // otherwise leave a dead import for the linter to trip over.
  const bands = [...new Set(m.items.map((it) => costExpression(it)))]
    .filter((e) => /^[A-Z_]+$/.test(e))
    .sort();
  if (bands.length) {
    lines.push(`import { ${bands.join(", ")} } from "./tokenEconomy";`);
    lines.push("");
  }
  lines.push(`export const OUTFIT_IDS = [`);
  for (const it of m.items) lines.push(`  "${it.id}",`);
  lines.push(`] as const;`);
  lines.push(`export type OutfitId = (typeof OUTFIT_IDS)[number];`);
  lines.push("");
  lines.push(`/**`);
  lines.push(` * Which slot a piece occupies.`);
  lines.push(` *`);
  lines.push(` *   garment    the whole body, top and bottom at once (a saree, a sherwani)`);
  lines.push(` *   top        her upper half only, worn with a bottom`);
  lines.push(` *   bottom     her lower half only; NEVER worn without a top`);
  lines.push(` *   accessory  her head`);
  lines.push(` *`);
  lines.push(` * "garment" is the original whole-body kind and keeps its name so the six`);
  lines.push(` * pieces that predate two-part clothing need no migration.`);
  lines.push(` */`);
  lines.push(`export type OutfitKind = "garment" | "top" | "bottom" | "accessory";`);
  lines.push(`/** How the shop should crop this item's preview: the whole bird, or her head. */`);
  lines.push(`export type OutfitPreview = "full" | "head";`);
  lines.push(`/** Which Bazaar door stocks it. */`);
  lines.push(`export type OutfitShopDoor = "tailor" | "station";`);
  lines.push("");
  lines.push(`export type OutfitCatalogEntry = {`);
  lines.push(`  id: OutfitId;`);
  lines.push(`  name: string;`);
  lines.push(`  tagline: string;`);
  lines.push(`  cost: number;`);
  lines.push(`  kind: OutfitKind;`);
  lines.push(`  preview: OutfitPreview;`);
  lines.push(`  shop: OutfitShopDoor;`);
  lines.push(`};`);
  lines.push("");
  lines.push(`export const OUTFIT_CATALOG: readonly OutfitCatalogEntry[] = [`);
  for (const it of m.items) {
    lines.push(`  {`);
    lines.push(`    id: "${it.id}",`);
    lines.push(`    name: ${JSON.stringify(it.name)},`);
    lines.push(`    tagline: ${JSON.stringify(it.tagline)},`);
    lines.push(`    cost: ${costExpression(it)},`);
    lines.push(`    kind: "${it.kind}",`);
    lines.push(`    preview: "${it.preview}",`);
    lines.push(`    shop: "${it.shop}",`);
    lines.push(`  },`);
  }
  lines.push(`];`);
  lines.push("");
  return { path: join(ROOT, "artifacts/api-server/src/lib/outfits.catalog.gen.ts"), body: lines.join("\n") };
}

function mobileHasPoses(id, prefix) {
  return POSES.every((p) => existsSync(join(MOBILE_OUT, id, `${prefix}-${p}.png`)));
}

function genMobileMap(m) {
  const lines = [];
  lines.push(GEN_HEADER.replace(/\n$/, ""));
  lines.push(`// Metro needs literal require() paths, which is why this file exists at all:`);
  lines.push(`// the map cannot be built from a loop at runtime. Only items whose pose`);
  lines.push(`// files are actually installed appear; a pose a client has not shipped`);
  lines.push(`// falls back to canonical Bolo rather than blanking her (mascotSource).`);
  lines.push(`import type { MascotPose } from '@/components/Mascot';`);
  lines.push("");
  lines.push(`export const OUTFIT_POSE_SOURCES: Record<`);
  lines.push(`  string,`);
  lines.push(`  Partial<Record<MascotPose, number>>`);
  lines.push(`> = {`);
  for (const it of m.items) {
    if (!mobileHasPoses(it.id, "mascot")) continue;
    lines.push(`  ${it.id.includes("-") ? `'${it.id}'` : it.id}: {`);
    for (const p of POSES) {
      lines.push(`    ${p}: require('../assets/images/mascot/outfits/${it.id}/mascot-${p}.png'),`);
    }
    lines.push(`  },`);
  }
  lines.push(`};`);
  lines.push("");
  lines.push(`export const ACCESSORY_OVERLAY_SOURCES: Record<`);
  lines.push(`  string,`);
  lines.push(`  Partial<Record<MascotPose, number>>`);
  lines.push(`> = {`);
  for (const it of m.items) {
    if (it.kind !== "accessory" || !mobileHasPoses(it.id, "overlay")) continue;
    lines.push(`  ${it.id.includes("-") ? `'${it.id}'` : it.id}: {`);
    for (const p of POSES) {
      lines.push(`    ${p}: require('../assets/images/mascot/outfits/${it.id}/overlay-${p}.png'),`);
    }
    lines.push(`  },`);
  }
  lines.push(`};`);
  lines.push("");
  return { path: join(ROOT, "artifacts/bolo-mobile/lib/mascotOutfits.gen.ts"), body: lines.join("\n") };
}

function genShopSets(m) {
  const station = m.items.filter((i) => i.shop === "station").map((i) => i.id);
  const mobile = [
    GEN_HEADER.replace(/\n$/, ""),
    `/** The Station Master's rack; the Tailor sells everything else. */`,
    `export const STATION_IDS: ReadonlySet<string> = new Set([${station.map((s) => `'${s}'`).join(", ")}]);`,
    "",
  ].join("\n");
  const web = [
    GEN_HEADER.replace(/\n$/, ""),
    `/** The Station Master's rack; the Tailor sells everything else. */`,
    `export const STATION_IDS: ReadonlySet<string> = new Set([${station.map((s) => `"${s}"`).join(", ")}]);`,
    "",
  ].join("\n");
  return [
    { path: join(ROOT, "artifacts/bolo-mobile/lib/wardrobeShop.gen.ts"), body: mobile },
    { path: join(ROOT, "artifacts/gujarati-coach/src/lib/wardrobeShop.gen.ts"), body: web },
  ];
}

function generated() {
  const m = manifest();
  return [genServerCatalog(m), genMobileMap(m), ...genShopSets(m)];
}

function codegen({ write = true } = {}) {
  let stale = 0;
  for (const g of generated()) {
    const current = existsSync(g.path) ? readFileSync(g.path, "utf8") : null;
    if (current === g.body) continue;
    stale += 1;
    if (write) {
      writeFileSync(g.path, g.body);
      console.log(`wrote ${g.path.replace(ROOT + "/", "")}`);
    } else {
      console.error(`STALE: ${g.path.replace(ROOT + "/", "")} does not match the manifest`);
    }
  }
  if (write && stale === 0) console.log("registries already match the manifest");
  return stale;
}

// ---------------------------------------------------------------------------
// check: the promise that the manifest, the registries and the shipped art
// agree. Run it in place of remembering.
// ---------------------------------------------------------------------------
function pngSize(path) {
  const b = readFileSync(path);
  // IHDR: width/height at bytes 16..24 of any valid PNG.
  return { w: b.readUInt32BE(16), h: b.readUInt32BE(20) };
}

function check() {
  const m = manifest();
  const problems = [];
  for (const it of m.items) {
    for (const [name, dir] of [["mobile", MOBILE_OUT], ["web", WEB_OUT]]) {
      for (const p of POSES) {
        const f = join(dir, it.id, `mascot-${p}.png`);
        if (!existsSync(f)) {
          problems.push(`${it.id}: missing ${name} pose ${p}`);
          continue;
        }
        const { w, h } = pngSize(f);
        if (w !== SPRITE_W || h !== SPRITE_H) {
          problems.push(`${it.id}: ${name} ${p} is ${w}x${h}, not ${SPRITE_W}x${SPRITE_H}`);
        }
      }
      if (it.kind === "accessory") {
        for (const p of POSES) {
          if (!existsSync(join(dir, it.id, `overlay-${p}.png`)))
            problems.push(`${it.id}: missing ${name} overlay ${p}`);
        }
      }
    }
    if (it.art && !existsSync(join(ROOT, it.art))) problems.push(`${it.id}: source art ${it.art} is gone`);
  }
  for (const [name, dir] of [["mobile", MOBILE_OUT], ["web", WEB_OUT]]) {
    for (const d of readdirSync(dir, { withFileTypes: true })) {
      if (d.isDirectory() && !m.items.some((i) => i.id === d.name))
        problems.push(`orphan ${name} art dir with no manifest entry: ${d.name}`);
    }
  }
  const stale = codegen({ write: false });
  if (stale) problems.push(`${stale} generated registr${stale === 1 ? "y is" : "ies are"} stale — run codegen`);
  if (problems.length) {
    for (const p of problems) console.error(`✗ ${p}`);
    process.exit(1);
  }
  console.log(`✓ ${m.items.length} items: art on both clients, registries in step with the manifest`);
}

function montage() {
  const tiles = [];
  for (const it of manifest().items) {
    for (const p of POSES) tiles.push(join(WEB_OUT, it.id, `mascot-${p}.png`));
  }
  const out = join(REVIEW_DIR, `wardrobe-montage-${new Date().toISOString().slice(0, 10)}.png`);
  mkdirSync(REVIEW_DIR, { recursive: true });
  execFileSync("magick", ["montage", ...tiles, "-tile", "5x", "-geometry", "160x160+3+3",
    "-background", "#eeeeee", out], { cwd: ROOT });
  console.log(`montage of every piece in every pose → ${out.replace(ROOT + "/", "")}`);
}

const [cmd, id] = process.argv.slice(2);
switch (cmd) {
  case "gen": gen(id); break;
  case "install": gen(id, { install: true }); codegen(); break;
  case "codegen": codegen(); break;
  case "check": check(); break;
  case "montage": montage(); break;
  // THE PLACEMENT TOOL. Its own process because it is a server and because
  // nothing else in this CLI is interactive: `wardrobe place`, then drag.
  case "place":
    execFileSync("node", ["scripts/wardrobe-place.mjs"], { stdio: "inherit" });
    break;
  case "list": for (const it of manifest().items) console.log(`${it.id.padEnd(14)} ${it.kind.padEnd(10)} ${it.shop.padEnd(8)} ${it.costBand.padEnd(10)} ${it.status}`); break;
  default:
    console.error("usage: wardrobe.mjs gen <id> | install <id> | place | codegen | check | montage | list");
    process.exit(1);
}
