import { Link } from "wouter";
import { motion } from "framer-motion";
import { ArrowLeft, Sparkles, RefreshCcw, WifiOff } from "lucide-react";
import { FunFactLoader } from "@/components/fun-fact-loader";

// The first time a learner opens a topic in a given language, the phrases are
// generated by AI on demand (a few seconds) and cached. These components make
// that wait feel like progress instead of a frozen spinner, and give a clear
// way to recover when generation fails.

function BuildingMessage({ languageName }: { languageName?: string }) {
  return (
    <div className="flex flex-col items-center text-center gap-3">
      <motion.div
        className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-primary/10 text-primary"
        animate={{ scale: [1, 1.08, 1] }}
        transition={{ duration: 1.6, repeat: Infinity, ease: "easeInOut" }}
      >
        <Sparkles className="w-8 h-8" />
      </motion.div>
      <div>
        <h2 className="text-xl font-black text-foreground">
          Building your {languageName ?? ""} lesson
        </h2>
        <p className="text-muted-foreground font-medium flex items-center justify-center gap-1 mt-1">
          Crafting fresh phrases just for you
          <span className="inline-flex gap-0.5">
            {[0, 1, 2].map((i) => (
              <motion.span
                key={i}
                className="w-1.5 h-1.5 rounded-full bg-muted-foreground/70"
                animate={{ opacity: [0.2, 1, 0.2] }}
                transition={{ duration: 1.2, repeat: Infinity, delay: i * 0.2 }}
              />
            ))}
          </span>
        </p>
      </div>
    </div>
  );
}

// Skeleton for the category detail page — mirrors its real layout so the shell
// stays put and only the content fills in.
export function CategoryLessonSkeleton({
  languageName,
  categoryTitle,
}: {
  languageName?: string;
  categoryTitle?: string;
}) {
  return (
    <div className="min-h-[100dvh] bg-background flex flex-col">
      <header className="sticky top-0 z-10 bg-background/80 backdrop-blur-md border-b border-border px-4 py-4 flex items-center justify-between">
        <Link
          href="/app"
          className="p-2 -ml-2 rounded-full hover:bg-muted text-foreground transition-colors button-spring"
        >
          <ArrowLeft className="w-6 h-6" />
        </Link>
        <div className="text-center">
          <h1 className="font-bold text-lg text-foreground">
            {categoryTitle ?? "Loading…"}
          </h1>
        </div>
        <div className="w-10" />
      </header>

      <main className="flex-1 p-6 space-y-6">
        <div className="bg-white rounded-3xl p-8 border-2 border-border shadow-sm flex flex-col items-center gap-6">
          <BuildingMessage languageName={languageName} />
          <FunFactLoader />
        </div>

        <div className="space-y-3">
          <div className="h-6 w-40 rounded-full bg-muted animate-pulse mx-2" />
          {Array.from({ length: 5 }).map((_, i) => (
            <div
              key={i}
              className="bg-white rounded-2xl p-4 border border-card-border shadow-sm flex items-start gap-4 animate-pulse"
              style={{ animationDelay: `${i * 0.12}s` }}
            >
              <div className="mt-1 w-6 h-6 rounded-full bg-muted shrink-0" />
              <div className="flex-1 space-y-2">
                <div className="h-6 w-2/3 rounded-md bg-muted" />
                <div className="h-4 w-1/3 rounded-md bg-muted" />
                <div className="h-4 w-1/2 rounded-md bg-muted" />
              </div>
              <div className="w-9 h-9 rounded-full bg-muted shrink-0" />
            </div>
          ))}
        </div>
      </main>
    </div>
  );
}

// Centered building state for the practice screen (which shows one card at a
// time rather than a list).
export function LessonBuildingScreen({
  languageName,
  backHref,
}: {
  languageName?: string;
  backHref: string;
}) {
  return (
    <div className="min-h-[100dvh] bg-background flex flex-col">
      <header className="px-6 py-4">
        <Link
          href={backHref}
          className="text-muted-foreground hover:text-foreground inline-flex"
        >
          <ArrowLeft className="w-8 h-8" />
        </Link>
      </header>
      <div className="flex-1 flex items-center justify-center px-8">
        <div className="bg-white rounded-[2rem] p-10 border border-card-border shadow-sm w-full max-w-sm flex flex-col items-center gap-6">
          <BuildingMessage languageName={languageName} />
          <FunFactLoader />
        </div>
      </div>
    </div>
  );
}

// Shown when lesson generation fails (the API returns 502). Gives a clear retry
// affordance instead of an endless spinner.
export function LessonErrorScreen({
  backHref,
  onRetry,
  isRetrying,
}: {
  backHref: string;
  onRetry: () => void;
  isRetrying: boolean;
}) {
  return (
    <div className="min-h-[100dvh] bg-background flex flex-col">
      <header className="px-6 py-4">
        <Link
          href={backHref}
          className="text-muted-foreground hover:text-foreground inline-flex"
        >
          <ArrowLeft className="w-8 h-8" />
        </Link>
      </header>
      <div className="flex-1 flex items-center justify-center px-8">
        <div className="bg-white rounded-[2rem] p-8 border border-card-border shadow-sm w-full max-w-sm text-center flex flex-col items-center gap-4">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-destructive/10 text-destructive">
            <WifiOff className="w-8 h-8" />
          </div>
          <div>
            <h2 className="text-xl font-black text-foreground">
              The train's running a little late
            </h2>
            <p className="text-muted-foreground font-medium mt-1">
              This stop didn't load. Give it another go and we'll get you
              boarded.
            </p>
          </div>
          <button
            onClick={onRetry}
            disabled={isRetrying}
            className="w-full bg-primary text-primary-foreground font-bold text-lg py-4 px-6 rounded-2xl flex items-center justify-center gap-3 shadow-[0_6px_0_hsl(var(--primary-shadow))] active:translate-y-1.5 active:shadow-[0_0px_0_hsl(var(--primary-shadow))] transition-all disabled:opacity-60"
          >
            <RefreshCcw
              className={`w-5 h-5 ${isRetrying ? "animate-spin" : ""}`}
            />
            <span>{isRetrying ? "Trying again…" : "Try again"}</span>
          </button>
          <Link
            href={backHref}
            className="text-muted-foreground font-bold text-sm py-2"
          >
            Back to the journey
          </Link>
        </div>
      </div>
    </div>
  );
}
