import {
  pgTable,
  serial,
  text,
  boolean,
  integer,
  index,
  timestamp,
} from "drizzle-orm/pg-core";

// One person's traced alphabet, submitted from the public page at
// /aksharmala.html.
//
// WHY THIS TABLE EXISTS. Script Trace can show a learner a letter's SHAPE,
// because the guides are extracted from font outlines. It cannot show the ORDER
// the strokes go in or which way each one travels, because a font does not
// carry either, and those are the two things the scorer already has fault codes
// for. Only someone who writes the script can supply them, and asking a relative
// to paste a wall of numbers into a message does not survive the second
// contributor. So the page posts here instead.
//
// NO USER ID, deliberately. Contributors are family members who have never
// signed in and never will; requiring an account would cost more submissions
// than it would protect. Same posture as contact_submissions, which is public
// for the same reason.
export const scriptTraceContributionsTable = pgTable(
  "script_trace_contributions",
  {
    id: serial("id").primaryKey(),
    // One row per sitting, not per letter.
    //
    // THE PAGE AUTOSAVES AFTER EVERY LETTER, because a contributor can stop at
    // any point and the alternative loses everything they did. Each save sends
    // the whole set so far and upserts on this id, so the row always holds
    // their latest state and a person who traced nine letters and put the phone
    // down has nine letters stored rather than none.
    //
    // Generated by the browser. It identifies a sitting, nothing else.
    sessionId: text("session_id").notNull().unique(),
    // The script's display name as the page offered it, e.g. "Gujarati".
    // Stored as given rather than as an id so a submission stays readable even
    // if the roster is renamed later.
    script: text("script").notNull(),
    // First name as typed, or "-" when they did not say. Not identifying on its
    // own and not meant to be: it exists so that when two people disagree about
    // a letter you know which one to ask.
    contributor: text("contributor").notNull(),
    // The contributor ticked "I am just trying this out".
    //
    // Kept rather than rejected, and this is the point of the column: the first
    // person to open the page is whoever built it, and they may not write the
    // script at all. A practice run has to be visibly a practice run in the
    // DATA, because "remember to ignore mine" does not survive a handover.
    // Every read path filters on this by default.
    isPractice: boolean("is_practice").notNull().default(false),
    // How many letters this submission covers, denormalised so the obvious
    // question ("has anyone finished an alphabet yet") is a query and not a
    // parse of every row.
    glyphCount: integer("glyph_count").notNull(),
    // The wire format verbatim, e.g.
    //   bolo1|Gujarati|Ba|gu_a:12,30;20,58~74,26;74,78|...
    // Raw rather than shredded into rows: it is small, it is the thing the
    // page actually produced, and parseTracePayload is the one parser. Storing
    // a second representation would mean two parsers that can disagree.
    payload: text("payload").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    // Updated on every autosave, so the difference from created_at is how long
    // somebody spent, and a stale updated_at marks an abandoned sitting.
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => ({
    // The two questions actually asked of this table: what has come in for a
    // script, and what came in most recently.
    scriptIdx: index("stc_script_idx").on(table.script),
    createdAtIdx: index("stc_created_at_idx").on(table.createdAt),
  }),
);

export type ScriptTraceContribution =
  typeof scriptTraceContributionsTable.$inferSelect;
