const { getDefaultConfig } = require('expo/metro-config');

const config = getDefaultConfig(__dirname);

// The 3D stage (components/bolo3d) ships as two assets: the page the WebView
// shows (stage.html, generated by lib/bolo-stage/build.mjs) and the character
// model (.glb). Metro only bundles file types it knows, so both are declared.
config.resolver.assetExts.push('glb', 'html');

module.exports = config;
